### PR TITLE
Add step to publish to GitHub package registry

### PR DESCRIPTION
**Pull request by bekahs4**
### Summary

Add a step to the `release-please.yml` GitHub Actions workflow that publishes to the Fastly internal GItHub package registry [as discussed in Slack](https://fastly.slack.com/archives/C022F76SJ83/p1707421784242279).

### CODE REVIEW

**Review by guybedford — APPROVED** [review]
Looks good, happy to merge and try this out for the next release. I suppose we should just run with this approach for all `@fastly` packages until GitHub come up with a solution.

**Comment by bekahs4** [comment]
Thanks @guybedford. Looks like I still have a failing test after a re-run. Do you have any insight on what's going on with that? I don't expect this PR to be related to the test failure.

**Comment by guybedford** [comment]
@bekahs4 the CI issue is unrelated, so I've gone ahead and landed this in the mean time - will apply for the next release.

**Comment by bekahs4** [comment]
Thanks @guybedford!

**Comment by guybedford** [comment]
@bekahs4 I see the first release just failed here - https://github.com/fastly/js-compute-runtime/actions/runs/7979097116/job/21785698469 due to credentials. Any ideas at what level we need to address that? Happy to take follow-ups as necessary here.

**Comment by bekahs4** [comment]
@guybedford I'll try to take a look at this later with @psbanka. On first glance I would be surprised if the `release` job failure is related to this change because this PR only made changes to the `publish` job.

**Comment by guybedford** [comment]
Taking a look at that further, I believe this is also unrelated to this PR, and rather a separate issue with the release check. We can verify this properly when we tag the next release though, and if there are any issues with the GitHub package publish we can follow-up at that time.

**Comment by bekahs4** [comment]
Thanks for taking another look @guybedford. For planning purposes on our end, is there a timeline for the next tagged release?

**Comment by guybedford** [comment]
@bekahs4 v3.8.3 just went out and it looks like the GitHub release worked correctly.

**Pull request merged**
