### PR TITLE
AOT compilation: update to weval 0.2.12.

### PR DESCRIPTION
**Pull request by cfallin**
This includes a fix for irreducible control flow; see [this PR](https://github.com/cfallin/waffle/pull/13) in waffle.

### CODE REVIEW

**Comment by cfallin** [comment]
@guybedford @elliottt I've intentionally avoided a submodule update here as we have the open issue with the new headers implementation in StarlingMonkey interacting with weval somehow in debug builds; the version of weval pulled in by the `package.json` here is used by the js-compute-runtime toplevel driver, separately from the version of weval that the StarlingMonkey submodule uses.

**Comment by cfallin** [comment]
Hmm, this is triggering some issues deep in the Wasm backend; I need to investigate further.

**Comment by guybedford** [comment]
> @guybedford @elliottt I've intentionally avoided a submodule update here as we have the open issue with the new headers implementation in StarlingMonkey interacting with weval somehow in debug builds;

For what it is worth, the new headers work landed already in js-compute-runtime without any error, so we are already on the latest StarlingMonkey here. But fine to maintain separate versioning as well!

**Comment by cfallin** [comment]
I've pushed a new version of weval (0.2.12) with some additional fixes that I believe should pass tests now (let's see how CI does); analogous update in StarlingMonkey at bytecodealliance/StarlingMonkey#141.

> For what it is worth, the new headers work landed already in js-compute-runtime without any error, so we are already on the latest StarlingMonkey here. But fine to maintain separate versioning as well!

Ah, interesting, and we're passing WPT here still -- I had been worried about hitting the same issue as bytecodealliance/StarlingMonkey#114 but I guess for whatever reason we don't see that here? In any case, I'm happy to do a separate PR to update to latest StarlingMonkey once above PR lands too, or land it first and update this one, either way.

**Review by guybedford — APPROVED** [review]

**Pull request merged**
